project:
  type: website
  output-dir: docs

website:
  title: "Guillem Rico"
  navbar:
    background: light
    right:
      - href: index.qmd
        text: About
      - research.qmd
      - teaching.qmd
  search: false
  favicon: gr_favicon-32x32.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header: <meta name="google-site-verification" content="M2gcz0Qi-sf6BbfxKDtSYl5ojIThhJ4SzzeVh0Ikpjk" />

editor: source

